export const REGISTRATION_REQUEST = 'AUTH/REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'AUTH/REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'AUTH/REGISTRATION_FAILED';
export const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_FAILED = 'AUTH/LOGIN_FAILED';
export const SWITCH_AUTH = 'AUTH/SWITCH_AUTH';