export const GET_PROJECT_LIST_REQUEST = 'PROJECT/GET_PROJECT_LIST_REQUEST';
export const GET_PROJECT_LIST_SUCCESS = 'PROJECT/GET_PROJECT_LIST_SUCCESS';
export const GET_PROJECT_LIST_FAILED = 'PROJECT/GET_PROJECT_LIST_FAILED';

export const CREATE_PROJECT_LIST_REQUEST = 'PROJECT/CREATE_PROJECT_LIST_REQUEST';
export const CREATE_PROJECT_LIST_SUCCESS = 'PROJECT/CREATE_PROJECT_LIST_SUCCESS';
export const CREATE_PROJECT_LIST_FAILED = 'PROJECT/CREATE_PROJECT_LIST_FAILED';

export const REMOVE_PROJECT_REQUEST = 'PROJECT/REMOVE_PROJECT_LIST_REQUEST';
export const REMOVE_PROJECT_SUCCESS = 'PROJECT/REMOVE_PROJECT_SUCCESS';
export const REMOVE_PROJECT_FAILED = 'PROJECT/REMOVE_PROJECT_FAILED';

export const EDIT_PROJECT_REQUEST = 'PROJECT/EDIT_PROJECT_REQUEST';
export const EDIT_PROJECT_SUCCESS = 'PROJECT/EDIT_PROJECT_SUCCESS';
export const EDIT_PROJECT_FAILED = 'PROJECT/EDIT_PROJECT_FAILED';