export const GET_TASK_LIST_REQUEST = 'TASK/GET_TASK_LIST_REQUEST';
export const GET_TASK_LIST_SUCCESS = 'TASK/GET_TASK_LIST_SUCCESS';
export const GET_TASK_LIST_FAILED = 'TASK/GET_TASK_LIST_FAILED';

export const CREATE_TASK_REQUEST = 'TASK/CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'TASK/CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILED = 'TASK/CREATE_TASK_FAILED';

export const REMOVE_TASK_REQUEST = 'TASK/REMOVE_TASK_REQUEST';
export const REMOVE_TASK_SUCCESS = 'TASK/REMOVE_TASK_SUCCESS';
export const REMOVE_TASK_FAILED = 'TASK/REMOVE_TASK_FAILED';

export const EDIT_TASK_REQUEST = 'TASK/EDIT_TASK_REQUEST';
export const EDIT_TASK_SUCCESS = 'TASK/EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILED = 'TASK/EDIT_TASK_FAILED';